server:
  port: 8888
spring:
  datasource:
    username: wsh2022
    password: 123456
    url: jdbc:mysql://localhost:3306/tms_server?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml