server:
  port: 8081
spring:
  datasource:
    username: root
    password: A56923391a?
    url: jdbc:mysql://localhost:3306/tms_server?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: TMS管理系统
  try-host: http://localhost:${server.port}

myfun:
  jwt:
    header: Authorization
    # ===== 7天 单位秒 ===== #
    expire: 604800
    secret: a56923391a50825194a1781127309awu

